name = "JuliaFFT"
uuid = "58eb6a7f-78fe-4bda-ae9c-fba74f78ab46"
authors = ["Will M. Farr <wfarr@flatironinstitute.org>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
